programs:
    instant-crash:
        cmd: "/home/arthour/go/src/taskmaster/programs/instant-crash"
        numprocs: 1
        umask: 077
        workingdir: ./tmp
        autostart: true
        autorestart: unexpected
        exitcodes:
            - 0
        startretries: 2
        starttime: 5
        stopsignal: TERM
        stoptime: 1
        stdout: ./tmp/instant-crash.stdout
        stderr: ./tmp/instant-crash.stderr
        env:
    loop-print:
        cmd: "/home/arthour/go/src/taskmaster/programs/loop-print"
        numprocs: 3
        umask: 077
        workingdir: ./tmp
        autostart: true
        autorestart: unexpected
        exitcodes:
            - 0
            - 15
        startretries: 2
        starttime: 5
        stopsignal: TERM
        stoptime: 1
        stdout: ./tmp/loop-print.stdout
        stderr: ./tmp/loop-print.stderr
        env:
    wait-5sec-and-exit-success:
        cmd: "/home/arthour/go/src/taskmaster/programs/wait-5sec-and-exit-success"
        numprocs: 1
        umask: 077
        workingdir: ./tmp
        autostart: true
        autorestart: never
        exitcodes:
            - 0
        startretries: 2
        starttime: 5
        stopsignal: TERM
        stoptime: 1
        stdout: ./tmp/wait-5sec-and-exit-success.stdout
        stderr: ./tmp/wait-5sec-and-exit-success.stderr
        env:
    wait-5sec-and-exit-success-nostart:
        cmd: "/home/arthour/go/src/taskmaster/programs/wait-5sec-and-exit-success"
        numprocs: 1
        umask: 077
        workingdir: ./tmp
        autostart: false
        autorestart: always
        exitcodes:
            - 0
        startretries: 2
        starttime: 5
        stopsignal: TERM
        stoptime: 1
        stdout: ./tmp/wait-5sec-and-exit-success.stdout
        stderr: ./tmp/wait-5sec-and-exit-success.stderr
        env:
    loop-print-sig:
        cmd: "/home/arthour/go/src/taskmaster/programs/loop-print-signal"
        numprocs: 1
        umask: 077
        workingdir: ./tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
        startretries: 2
        starttime: 5
        stopsignal: INT
        stoptime: 10
        stdout: ./tmp/loop-print-sig.stdout
        stderr: ./tmp/loop-print-sig.stderr
        env:
