programs:
    write:
        cmd: "/home/arthour/go/src/taskmaster/programs/loop-write-file"
        numprocs: 1
        umask: 022
        workingdir: ./tmp/write/
        autostart: true
        autorestart: unexpected
        exitcodes:
            - 0
        startretries: 1
        starttime: 1
        stopsignal: INT
        stoptime: 1
        stdout: ./tmp/loop-write-file.stdout
        stderr: ./tmp/loop-write-file.stderr
        env: ["WHERE=here.txt"]
